// <auto-generated />
using System;
using FlightBookingSystem_DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightBookingSystem_DAL.Migrations
{
    [DbContext(typeof(Context.DatabaseContext))]
    [Migration("20250411152805_flight")]
    partial class flight
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.Admin", b =>
                {
                    b.Property<int>("MaAdmin")
                        .HasColumnType("int");

                    b.Property<string>("KinhNghiem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaAdmin");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.ChiTietVe", b =>
                {
                    b.Property<string>("MaChiTietVe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("GiaVe")
                        .HasColumnType("real");

                    b.Property<string>("MaChuyenBay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaGhe")
                        .HasColumnType("int");

                    b.Property<string>("MaHL")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThaiVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChiTietVe");

                    b.HasIndex("MaChuyenBay");

                    b.HasIndex("MaGhe")
                        .IsUnique();

                    b.HasIndex("MaHL")
                        .IsUnique();

                    b.HasIndex("MaVe");

                    b.ToTable("ChiTietVe", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.ChuyenBay", b =>
                {
                    b.Property<string>("MaChuyenBay")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTuyenBay")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SoHieuMB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianDen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianDi")
                        .HasColumnType("datetime2");

                    b.HasKey("MaChuyenBay");

                    b.HasIndex("MaTuyenBay");

                    b.HasIndex("SoHieuMB");

                    b.ToTable("ChuyenBay", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.DonHang", b =>
                {
                    b.Property<string>("MaDH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDatHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 11, 22, 28, 4, 675, DateTimeKind.Local).AddTicks(4282));

                    b.Property<float>("TongGiaTriDonHang")
                        .HasColumnType("real");

                    b.HasKey("MaDH");

                    b.HasIndex("MaKH");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.DonHangKhuyenMai", b =>
                {
                    b.Property<string>("MaDHKM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaDHKM");

                    b.HasIndex("MaKM");

                    b.ToTable("DonHangKhuyenMai", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.DonHangOffline", b =>
                {
                    b.Property<string>("MaDHOffline")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.HasKey("MaDHOffline");

                    b.HasIndex("MaNV");

                    b.ToTable("DonHangOffline", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.Ghe", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGhe"));

                    b.Property<string>("HangGhe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("PHOTHONG");

                    b.Property<string>("SoHieuMB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThaiGhe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Còn trống");

                    b.HasKey("MaGhe");

                    b.HasIndex("SoHieuMB");

                    b.ToTable("Ghe", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.GiaVeChuyenBay", b =>
                {
                    b.Property<int>("MaHangGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHangGhe"));

                    b.Property<float>("GiaVe")
                        .HasColumnType("real");

                    b.Property<string>("LoaiGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaHangGhe");

                    b.HasIndex("MaCB");

                    b.ToTable("GiaVeChuyenBay", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.HangMayBay", b =>
                {
                    b.Property<string>("SoHieuHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("SoHieuHang");

                    b.ToTable("HangHangKhong", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.HanhLy", b =>
                {
                    b.Property<string>("MaHL")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("ChiPhi")
                        .HasColumnType("real");

                    b.Property<string>("MoTaHL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrongLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHL");

                    b.ToTable("HanhLy", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("HangThanhVien")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Đồng");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.KhuVuc", b =>
                {
                    b.Property<string>("MaKhuVuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhuVuc");

                    b.ToTable("KhuVuc", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.KhuyenMai", b =>
                {
                    b.Property<string>("MaKM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<float>("TyLeGiam")
                        .HasColumnType("real");

                    b.HasKey("MaKM");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.LichBay", b =>
                {
                    b.Property<string>("MaLich")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaChuyenBay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLapLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 11, 22, 28, 4, 717, DateTimeKind.Local).AddTicks(5981));

                    b.HasKey("MaLich");

                    b.HasIndex("MaChuyenBay")
                        .IsUnique();

                    b.HasIndex("MaNV");

                    b.ToTable("LichBay", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.MayBay", b =>
                {
                    b.Property<string>("SoHieuMB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoHieuHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SoHieuMB");

                    b.HasIndex("SoHieuHang");

                    b.ToTable("MayBay", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.NguoiDung", b =>
                {
                    b.Property<int>("IdNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNguoiDung"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 11, 22, 28, 4, 640, DateTimeKind.Local).AddTicks(630));

                    b.Property<string>("SoCCCD")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdNguoiDung");

                    b.HasIndex("SoCCCD")
                        .IsUnique()
                        .HasFilter("[SoCCCD] IS NOT NULL");

                    b.HasIndex("SoDienThoai")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Luong")
                        .HasColumnType("real");

                    b.Property<DateTime>("NgayVaoLam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 11, 22, 28, 4, 667, DateTimeKind.Local).AddTicks(5162));

                    b.HasKey("MaNV");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.SanBay", b =>
                {
                    b.Property<string>("MaSanBay")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaKhuVuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaSanBay");

                    b.HasIndex("MaKhuVuc");

                    b.ToTable("SanBay", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.SanBayTrungGian", b =>
                {
                    b.Property<string>("MaSanBayTrungGian")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaChuyenBay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSanBay")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTuyenBay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianDungChan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTiepTuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSanBayTrungGian");

                    b.HasIndex("MaChuyenBay");

                    b.HasIndex("MaSanBay")
                        .IsUnique();

                    b.ToTable("SanBayTrungGian", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.TaiKhoan", b =>
                {
                    b.Property<int>("idTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTaiKhoan"));

                    b.Property<int>("IdNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("User");

                    b.HasKey("idTaiKhoan");

                    b.HasIndex("IdNguoiDung")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.ThanhToan", b =>
                {
                    b.Property<string>("MaThanhToan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaDH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 11, 22, 28, 4, 693, DateTimeKind.Local).AddTicks(6411));

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SoTien")
                        .HasColumnType("real");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDH")
                        .IsUnique();

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.TuyenBay", b =>
                {
                    b.Property<string>("MaTuyenBay")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSanBayDen")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSanBayDi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaTuyenBay");

                    b.HasIndex("MaSanBayDen");

                    b.HasIndex("MaSanBayDi");

                    b.ToTable("TuyenBay", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.Ve", b =>
                {
                    b.Property<string>("MaVe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaNguoiSoHuu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayXuatVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 4, 11, 22, 28, 4, 724, DateTimeKind.Local).AddTicks(1737));

                    b.HasKey("MaVe");

                    b.HasIndex("MaDH");

                    b.HasIndex("MaNguoiSoHuu");

                    b.ToTable("Ve", (string)null);
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.Admin", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.NguoiDung", "NguoiDung")
                        .WithOne("Admin")
                        .HasForeignKey("FlightBookingSystem_DAL.Model.Admin", "MaAdmin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.ChiTietVe", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.ChuyenBay", "ChuyenBay")
                        .WithMany("ChiTietVes")
                        .HasForeignKey("MaChuyenBay")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem_DAL.Model.Ghe", "Ghe")
                        .WithOne("ChiTietVe")
                        .HasForeignKey("FlightBookingSystem_DAL.Model.ChiTietVe", "MaGhe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem_DAL.Model.HanhLy", "HanhLy")
                        .WithOne("ChiTietVe")
                        .HasForeignKey("FlightBookingSystem_DAL.Model.ChiTietVe", "MaHL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem_DAL.Model.Ve", "Ve")
                        .WithMany("ChiTietVes")
                        .HasForeignKey("MaVe")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChuyenBay");

                    b.Navigation("Ghe");

                    b.Navigation("HanhLy");

                    b.Navigation("Ve");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.ChuyenBay", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.TuyenBay", "TuyenBay")
                        .WithMany("ChuyenBays")
                        .HasForeignKey("MaTuyenBay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem_DAL.Model.MayBay", "MayBay")
                        .WithMany("ChuyenBays")
                        .HasForeignKey("SoHieuMB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MayBay");

                    b.Navigation("TuyenBay");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.DonHang", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.DonHangKhuyenMai", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.DonHang", "DonHang")
                        .WithOne("DonHangKhuyenMai")
                        .HasForeignKey("FlightBookingSystem_DAL.Model.DonHangKhuyenMai", "MaDHKM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem_DAL.Model.KhuyenMai", "KhuyenMai")
                        .WithMany("DonHangKhuyenMais")
                        .HasForeignKey("MaKM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.DonHangOffline", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.DonHang", "DonHang")
                        .WithOne("DonHangOffline")
                        .HasForeignKey("FlightBookingSystem_DAL.Model.DonHangOffline", "MaDHOffline")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem_DAL.Model.NhanVien", "NhanVien")
                        .WithMany("DonHangOfflines")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.Ghe", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.MayBay", "MayBay")
                        .WithMany("Ghes")
                        .HasForeignKey("SoHieuMB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MayBay");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.GiaVeChuyenBay", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.ChuyenBay", "ChuyenBay")
                        .WithMany("GiaVeChuyenBays")
                        .HasForeignKey("MaCB")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChuyenBay");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.KhachHang", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.NguoiDung", "NguoiDung")
                        .WithOne("KhachHang")
                        .HasForeignKey("FlightBookingSystem_DAL.Model.KhachHang", "MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.LichBay", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.ChuyenBay", "ChuyenBay")
                        .WithOne("LichBay")
                        .HasForeignKey("FlightBookingSystem_DAL.Model.LichBay", "MaChuyenBay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem_DAL.Model.NhanVien", "NhanVien")
                        .WithMany("LichBays")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenBay");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.MayBay", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.HangMayBay", "HangMayBay")
                        .WithMany("MayBays")
                        .HasForeignKey("SoHieuHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangMayBay");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.NhanVien", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.NguoiDung", "NguoiDung")
                        .WithOne("NhanVien")
                        .HasForeignKey("FlightBookingSystem_DAL.Model.NhanVien", "MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.SanBay", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.KhuVuc", "KhuVuc")
                        .WithMany("SanBays")
                        .HasForeignKey("MaKhuVuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuVuc");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.SanBayTrungGian", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.ChuyenBay", "ChuyenBay")
                        .WithMany("SanBayTrungGians")
                        .HasForeignKey("MaChuyenBay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem_DAL.Model.SanBay", "SanBay")
                        .WithOne("SanBayTrungGian")
                        .HasForeignKey("FlightBookingSystem_DAL.Model.SanBayTrungGian", "MaSanBay")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChuyenBay");

                    b.Navigation("SanBay");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.TaiKhoan", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.NguoiDung", "NguoiDung")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("FlightBookingSystem_DAL.Model.TaiKhoan", "IdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.ThanhToan", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.DonHang", "DonHang")
                        .WithOne("ThanhToan")
                        .HasForeignKey("FlightBookingSystem_DAL.Model.ThanhToan", "MaDH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.TuyenBay", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.SanBay", "SanBayDen")
                        .WithMany("TuyenBayDens")
                        .HasForeignKey("MaSanBayDen")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem_DAL.Model.SanBay", "SanBayDi")
                        .WithMany("TuyenBayDis")
                        .HasForeignKey("MaSanBayDi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SanBayDen");

                    b.Navigation("SanBayDi");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.Ve", b =>
                {
                    b.HasOne("FlightBookingSystem_DAL.Model.DonHang", "DonHang")
                        .WithMany("Ves")
                        .HasForeignKey("MaDH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlightBookingSystem_DAL.Model.NguoiDung", "NguoiDung")
                        .WithMany("Ves")
                        .HasForeignKey("MaNguoiSoHuu")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.ChuyenBay", b =>
                {
                    b.Navigation("ChiTietVes");

                    b.Navigation("GiaVeChuyenBays");

                    b.Navigation("LichBay")
                        .IsRequired();

                    b.Navigation("SanBayTrungGians");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.DonHang", b =>
                {
                    b.Navigation("DonHangKhuyenMai")
                        .IsRequired();

                    b.Navigation("DonHangOffline")
                        .IsRequired();

                    b.Navigation("ThanhToan")
                        .IsRequired();

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.Ghe", b =>
                {
                    b.Navigation("ChiTietVe")
                        .IsRequired();
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.HangMayBay", b =>
                {
                    b.Navigation("MayBays");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.HanhLy", b =>
                {
                    b.Navigation("ChiTietVe")
                        .IsRequired();
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.KhuVuc", b =>
                {
                    b.Navigation("SanBays");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.KhuyenMai", b =>
                {
                    b.Navigation("DonHangKhuyenMais");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.MayBay", b =>
                {
                    b.Navigation("ChuyenBays");

                    b.Navigation("Ghes");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.NguoiDung", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("KhachHang")
                        .IsRequired();

                    b.Navigation("NhanVien")
                        .IsRequired();

                    b.Navigation("TaiKhoan")
                        .IsRequired();

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.NhanVien", b =>
                {
                    b.Navigation("DonHangOfflines");

                    b.Navigation("LichBays");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.SanBay", b =>
                {
                    b.Navigation("SanBayTrungGian")
                        .IsRequired();

                    b.Navigation("TuyenBayDens");

                    b.Navigation("TuyenBayDis");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.TuyenBay", b =>
                {
                    b.Navigation("ChuyenBays");
                });

            modelBuilder.Entity("FlightBookingSystem_DAL.Model.Ve", b =>
                {
                    b.Navigation("ChiTietVes");
                });
#pragma warning restore 612, 618
        }
    }
}
